-- V1__Create_initial_tables.sql

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS tuition_offers (
    composite_key VARCHAR(255) PRIMARY KEY,
    class_level VARCHAR(255),
    description VARCHAR(2000),
    facebook_post_id VARCHAR(255),
    gender_preference VARCHAR(255),
    location VARCHAR(255),
    page_name VARCHAR(255),
    post_url VARCHAR(1000),
    salary VARCHAR(255),
    scraped_at TIMESTAMP(6),
    subject VARCHAR(255)
);
